#!/bin/sh

WPA_SUPPLICANT_FILE="/boot/wpa_supplicant.conf"

start() {
	echo "Starting..."
	if [ -e "$WPA_SUPPLICANT_FILE" ]; then
		mv $WPA_SUPPLICANT_FILE /etc/
		echo "/boot/wpa_supplicant.conf moved to /etc/. done."
	else
		echo "/boot/wpa_supplicant.conf not found, so no action. done."
	fi

	echo "Setting keyboard layout..."
	/usr/bin/loadkeys de.map

  # Create empty folder with root permissions
	echo "Fixing possible SSHD permission error..."
	mkdir /var/empty 2> /dev/null
}

stop() {
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
