#!/bin/sh

WPE_URL_FILE="/boot/url.txt"

start() {
	echo -n "Starting WPE: "
	if [ -e "$WPE_URL_FILE" ]; then
		URL=`head -1 $WPE_URL_FILE`
		if [ -n "$URL" ]; then
			/usr/bin/wpe --loop $URL &> /dev/null &
			echo "OK"
		else
			echo "NO URL"
		fi
	else
		echo "NO FILE"
	fi
	if [ -x "$(command -v psplash-write)" ]; then
  	/usr/bin/psplash-write "PROGRESS 90"
	fi
}

stop() {
	echo -n "Stopping WPE: "
	killall wpe WPELauncher WPEWebProcess WPENetworkProcess &> /dev/null
	echo "OK"
	if [ -x "$(command -v psplash-write)" ]; then
    /usr/bin/psplash-write "PROGRESS 90"
	fi
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
